ns: fix syntax expansion scoping issues
Previously ns was picking up refer (at least) indirectly (and
incorrectly), but recent guile changes fixed that, which caused builds
fail like this:

  ERROR: In procedure %resolve-variable:
  In procedure module-lookup: Unbound variable: refer

Rework the expansion to refer to the correct refer, and adjust other
ns directives to produce syntaxes rather than datums.

cf. 9e0f03c5fd36764827c8bb03887f14640c883b70

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>